Reference: https://towardsdatascience.com/historical-stock-price-data-in-python-a0b6dc826836

https://medium.com/@gokhalehemal11/how-to-scrape-financial-websites-using-python-requests-and-beautifulsoup-5f436318ca9

https://github.com/akhatri24/Web-Scraping/blob/main/Moneycontrol%20Data%20Pull.py

Magic Formula Key Points:
1. Set a minimum market capitalization for your portfolio companies. This should be typically higher than $100 million.
2. Ensure you exclude any financial or utility stocks when you choose your companies.
3. Exclude American Depository Receipts (ADRs). These are stocks in foreign companies.
4. Calculate each company's earnings yield (EBIT ÷ Enterprise Value).
5. Calculate each company's return on capital [EBIT ÷ (Net Fixed Assets + Working Capital)].
6. Rank selected companies by highest earnings yields and highest return on capital.
7. Buy two to three positions each month in the top 20 to 30 companies, over the course of a year.
8. Each year, rebalance the portfolio by selling off losers one week before the year term ends. Sell off winners one week after the year mark.
9. Repeat the process each year for a minimum of five to 10 years or more.

### Magic Formula

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
from multiprocessing.dummy import Pool as ThreadPool

In [4]:
tickers = ["ASTRAL.NS", "AARTIIND.NS", "BALRAMCHIN.NS", "BHARTIARTL.NS","BHEL.NS","BRITANNIA.NS", "BSOFT.NS", "CHAMBLFERT.NS","COLPAL.NS","CROMPTON.NS",
                   "CUB.NS","ESCORTS.NS","FEDERALBNK.NS","GMRINFRA.NS","HAL.NS","HAVELLS.NS","HDFCLIFE.NS","L&TFH.NS","MARUTI.NS","MFSL.NS","NMDC.NS","PEL.NS","RBLBANK.NS","TRENT.NS","VEDL.NS"]

In [5]:
tickers = ["astrallimited", "aartiindustries", "balrampurchinimills", "bhartiairtel","bharatheavyelectricals","britanniaindustries",
           "birlasoft", "chambalfertiliserschemicals","colgatepalmoliveindia","cromptongreavesconsumerelectrical",
                  "escortskubota","gmrairportsinfrastructure","hindustanaeronauticsltd","havellsindia","hdfclifeinsurancecompany","ltfinanceholdings","marutisuzukiindia",
           "maxfinancialservices","nmdc","piramalenterprises","trent","vedanta"]

In [6]:
sector = {}
sector["astrallimited"] = "plastics"
sector["aartiindustries"] = "chemicals"
sector["balrampurchinimills"] = "sugar"
sector["bhartiairtel"] = "telecommunications-service"
sector["bharatheavyelectricals"] = "infrastructure-general"
sector["britanniaindustries"] = "food-processing"
sector["birlasoft"] = "computers-software-mediumsmall"
# sector["canarabank"] = 
sector["chambalfertiliserschemicals"] = "fertilisers"
sector["colgatepalmoliveindia"] = "personal-care"


sector["cromptongreavesconsumerelectrical"] = "electricals"
sector["escortskubota"] = "automobile-tractors"
sector["gmrairportsinfrastructure"] = "transport-infrastructure"
sector["hindustanaeronauticsltd"] = "diversified"
sector["havellsindia"] = "electric-equipment"
sector["hdfclifeinsurancecompany"] = "lifehealth-insurance"


sector["ltfinanceholdings"] = "finance-investments"
sector["marutisuzukiindia"] = "auto-carsjeeps"
sector["maxfinancialservices"] = "finance-investments"
sector["nmdc"] = "miningminerals"

sector["piramalenterprises"] = "finance-nbfc"
sector["trent"] = "retail"
sector["vedanta"] = "miningminerals"

In [7]:
ti = ["APT02", "AI45", "BCM", "BA08","BHE","BI", "KPI02", "CB06","CFC","CPI","CGC01",
                   "E","GI27","HAL","HI01","HSL01","LFH","MS24","MI","NMD02","PH05","T04","SG"]

In [90]:
financial_dir = {}

In [91]:
url = "https://www.moneycontrol.com/financials/{}/balance-sheetVI/{}".format("relianceindustries","RI")
headers = {"User-Agent" : "Chrome/96.0.4664.110"}
page = requests.get(url, headers=headers)
page_content = page.content

In [92]:
url

'https://www.moneycontrol.com/financials/relianceindustries/balance-sheetVI/RI'

In [17]:
soup = BeautifulSoup(page_content,"html.parser")
tabl = soup.find_all("div" , {"class" : "tab-content"})
for t in tabl:
    heading = t.find_all("div" , {"class": "print-block"})
    print(t)

<div class="tab-content">
<div class="tab-pane in active" id="autosuggestlist">
<ul class="suglist scrollBar">
<li><a href="javascript:;" target="_parent"><span><b>Auri</b>ferous</span> Aqua Farma , 519363</a></li>
</ul>
</div>
</div>
<div class="tab-content clearfix">
<div class="tab-pane fade active in" id="new-format">
<div class="nsebsetab subnsebsetab clearfix">
<ul class="subtabs nav-tabs">
<li class="active"><a href="javascript:void();" id="#standalone">Standalone</a></li>
<li><a href="https://www.moneycontrol.com/financials/relianceindustries/consolidated-balance-sheetVI/RI#RI" id="#consolidated">Consolidated</a></li>
</ul>
<div class="print-block">
<form action="https://www.moneycontrol.com/stocks/company_info/print_main.php" id="print_frm" method="post" name="print_frm" target="_blank">
                                    Print/Copy to Excel :
                                    <span class="form small disb">
<input id="sc_did" name="sc_did" type="hidden" value="RI"/>
<select id="sel_opt" name="sel_opt">
<option value="0">- Standalone -</option>
<option value="1">Profit &amp; Loss</option>
<option value="2">Profit &amp; Loss (New)</option>
<option value="3">Balance Sheet</option>
<option selected='"selected"' value="4">Balance Sheet (New)</option>
<option value="5">Cash Flows</option>
<option value="6">Cash Flows (New)</option>
<option value="7">Quarterly</option>
<option value="8">Half Yearly</option>
<option value="9">Nine Monthly</option>
<option value="10">Yearly</option>
<option value="11">Capital Structure</option>
<option value="12">Raw Materials</option>
<option value="13">Finished Goods</option>
<option value="14">Financial Ratios</option>
<option value="15">Financial Ratios (New)</option>
<option value="16">- Consolidated - </option>
<option value="17">Quaterly</option>
<option value="18">Half Yearly</option>
<option value="19">Nine Monthly</option>
<option value="20">Yearly</option>
<option value="21">Profit &amp; Loss</option>
<option value="22">Profit &amp; Loss (New)</option>
<option value="23">Balance Sheet</option>
<option value="24">Balance Sheet (New)</option>
<option value="25">Cash Flows</option>
<option value="26">Cash Flows (New)</option>
<option value="27">Financial Ratios</option>
<option value="28">Financial Ratios (New)</option>
</select>
</span>
<a class="btn_common small_btn_common_go" href="javascript:void();" onclick="document.getElementById('print_frm').submit();" title="Go">Go</a>
</form>
</div>
</div>
<div class="tab-content">
<div class="tab-pane fade active in" id="standalone-new">
<div class="table-responsive financial-table">
<table class="mctable1" width="100%">
<tr class="lightbg">
<td>Balance Sheet of Reliance Industries <span class="ttn">(in Rs. Cr.)</span></td>
<td>Mar 23</td>
<td>Mar 22</td>
<td>Mar 21</td>
<td>Mar 20</td>
<td>Mar 19</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td> </td>
<td>12 mths</td>
<td>12 mths</td>
<td>12 mths</td>
<td>12 mths</td>
<td>12 mths</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="darkbg">
<td>EQUITIES AND LIABILITIES</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="darkbg">
<td>SHAREHOLDER'S FUNDS</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Equity Share Capital</td>
<td>6,765.00</td>
<td>6,765.00</td>
<td>6,445.00</td>
<td>6,339.00</td>
<td>6,339.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="lightbg">
<td>Total Share Capital</td>
<td>6,765.00</td>
<td>6,765.00</td>
<td>6,445.00</td>
<td>6,339.00</td>
<td>6,339.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Reserves and Surplus</td>
<td>472,328.00</td>
<td>464,762.00</td>
<td>468,038.00</td>
<td>384,875.00</td>
<td>398,983.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="lightbg">
<td>Total Reserves and Surplus</td>
<td>472,328.00</td>
<td>464,762.00</td>
<td>468,038.00</td>
<td>384,875.00</td>
<td>398,983.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="lightbg">
<td>Total Shareholders Funds</td>
<td>479,093.00</td>
<td>471,527.00</td>
<td>474,483.00</td>
<td>391,214.00</td>
<td>405,322.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="darkbg">
<td>NON-CURRENT LIABILITIES</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Long Term Borrowings</td>
<td>135,561.00</td>
<td>167,231.00</td>
<td>160,598.00</td>
<td>194,402.00</td>
<td>118,098.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Deferred Tax Liabilities [Net]</td>
<td>33,968.00</td>
<td>30,832.00</td>
<td>30,788.00</td>
<td>50,556.00</td>
<td>47,317.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Other Long Term Liabilities</td>
<td>3,370.00</td>
<td>6,504.00</td>
<td>4,518.00</td>
<td>3,434.00</td>
<td>504.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Long Term Provisions</td>
<td>1,296.00</td>
<td>1,598.00</td>
<td>1,499.00</td>
<td>1,410.00</td>
<td>2,483.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="lightbg">
<td>Total Non-Current Liabilities</td>
<td>174,195.00</td>
<td>206,165.00</td>
<td>197,403.00</td>
<td>249,802.00</td>
<td>168,402.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="darkbg">
<td>CURRENT LIABILITIES</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Short Term Borrowings</td>
<td>80,262.00</td>
<td>27,332.00</td>
<td>33,152.00</td>
<td>59,899.00</td>
<td>39,097.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Trade Payables</td>
<td>110,722.00</td>
<td>134,005.00</td>
<td>86,999.00</td>
<td>71,048.00</td>
<td>88,241.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Other Current Liabilities</td>
<td>45,367.00</td>
<td>38,749.00</td>
<td>80,735.00</td>
<td>198,662.00</td>
<td>73,900.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Short Term Provisions</td>
<td>926.00</td>
<td>896.00</td>
<td>901.00</td>
<td>1,073.00</td>
<td>783.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="lightbg">
<td>Total Current Liabilities</td>
<td>237,277.00</td>
<td>200,982.00</td>
<td>201,787.00</td>
<td>330,682.00</td>
<td>202,021.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="lightbg">
<td>Total Capital And Liabilities</td>
<td>890,565.00</td>
<td>878,674.00</td>
<td>873,673.00</td>
<td>971,699.00</td>
<td>775,745.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="darkbg">
<td>ASSETS</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="darkbg">
<td>NON-CURRENT ASSETS</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Tangible Assets</td>
<td>232,238.00</td>
<td>223,824.00</td>
<td>292,092.00</td>
<td>297,854.00</td>
<td>194,895.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Intangible Assets</td>
<td>12,926.00</td>
<td>15,802.00</td>
<td>14,741.00</td>
<td>8,624.00</td>
<td>8,293.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Capital Work-In-Progress</td>
<td>30,958.00</td>
<td>19,267.00</td>
<td>20,765.00</td>
<td>15,638.00</td>
<td>105,155.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Other Assets</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="lightbg">
<td>Fixed Assets</td>
<td>294,079.00</td>
<td>274,288.00</td>
<td>339,668.00</td>
<td>334,443.00</td>
<td>314,745.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Non-Current Investments</td>
<td>303,558.00</td>
<td>330,493.00</td>
<td>252,620.00</td>
<td>421,793.00</td>
<td>272,043.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Deferred Tax Assets [Net]</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Long Term Loans And Advances</td>
<td>22,448.00</td>
<td>41,951.00</td>
<td>65,698.00</td>
<td>44,348.00</td>
<td>31,806.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Other Non-Current Assets</td>
<td>4,548.00</td>
<td>9,544.00</td>
<td>4,968.00</td>
<td>4,461.00</td>
<td>4,287.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="lightbg">
<td>Total Non-Current Assets</td>
<td>624,633.00</td>
<td>656,276.00</td>
<td>662,954.00</td>
<td>805,045.00</td>
<td>622,881.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="darkbg">
<td>CURRENT ASSETS</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Current Investments</td>
<td>86,074.00</td>
<td>78,304.00</td>
<td>94,665.00</td>
<td>70,030.00</td>
<td>59,640.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Inventories</td>
<td>48,926.00</td>
<td>45,923.00</td>
<td>37,437.00</td>
<td>38,802.00</td>
<td>44,144.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Trade Receivables</td>
<td>16,898.00</td>
<td>14,394.00</td>
<td>4,159.00</td>
<td>7,483.00</td>
<td>12,110.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Cash And Cash Equivalents</td>
<td>56,811.00</td>
<td>21,714.00</td>
<td>5,573.00</td>
<td>8,485.00</td>
<td>3,768.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Short Term Loans And Advances</td>
<td>595.00</td>
<td>161.00</td>
<td>993.00</td>
<td>15,028.00</td>
<td>4,876.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>OtherCurrentAssets</td>
<td>56,628.00</td>
<td>61,902.00</td>
<td>67,892.00</td>
<td>26,826.00</td>
<td>28,326.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="lightbg">
<td>Total Current Assets</td>
<td>265,932.00</td>
<td>222,398.00</td>
<td>210,719.00</td>
<td>166,654.00</td>
<td>152,864.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="lightbg">
<td>Total Assets</td>
<td>890,565.00</td>
<td>878,674.00</td>
<td>873,673.00</td>
<td>971,699.00</td>
<td>775,745.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="darkbg">
<td>OTHER ADDITIONAL INFORMATION</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="darkbg">
<td>CONTINGENT LIABILITIES, COMMITMENTS</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Contingent Liabilities</td>
<td>27,421.00</td>
<td>30,426.00</td>
<td>25,921.00</td>
<td>45,924.00</td>
<td>111,869.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="darkbg">
<td>CIF VALUE OF IMPORTS</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Raw Materials</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Stores, Spares And Loose Tools</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Trade/Other Goods</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Capital Goods</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="darkbg">
<td>EXPENDITURE IN FOREIGN EXCHANGE</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Expenditure In Foreign Currency</td>
<td>413,231.00</td>
<td>321,119.00</td>
<td>134,436.00</td>
<td>260,280.00</td>
<td>307,558.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="darkbg">
<td>REMITTANCES IN FOREIGN CURRENCIES FOR DIVIDENDS</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Dividend Remittance In Foreign Currency</td>
<td>--</td>
<td>--</td>
<td>--</td>
<td>--</td>
<td>--</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="darkbg">
<td>EARNINGS IN FOREIGN EXCHANGE</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>FOB Value Of Goods</td>
<td>--</td>
<td>--</td>
<td>--</td>
<td>--</td>
<td>--</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Other Earnings</td>
<td>576,842.00</td>
<td>245,752.00</td>
<td>179,929.00</td>
<td>284,196.00</td>
<td>214,337.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="darkbg">
<td>BONUS DETAILS</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Bonus Equity Share Capital</td>
<td>5,188.89</td>
<td>5,188.89</td>
<td>5,188.89</td>
<td>5,188.89</td>
<td>5,188.89</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="darkbg">
<td>NON-CURRENT INVESTMENTS</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Non-Current Investments Quoted Market Value</td>
<td>2,934.00</td>
<td>62,401.00</td>
<td>21,240.00</td>
<td>27,475.00</td>
<td>12,937.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Non-Current Investments Unquoted Book Value</td>
<td>303,180.00</td>
<td>273,377.00</td>
<td>235,348.00</td>
<td>394,521.00</td>
<td>259,314.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="darkbg">
<td>CURRENT INVESTMENTS</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Current Investments Quoted Market Value</td>
<td>65,984.00</td>
<td>21,471.00</td>
<td>36,303.00</td>
<td>31,814.00</td>
<td>24,017.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Current Investments Unquoted Book Value</td>
<td>20,090.00</td>
<td>56,833.00</td>
<td>58,362.00</td>
<td>38,216.00</td>
<td>35,623.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
</table>
</div>
<div class="source-line"><span>Source :</span> Dion Global Solutions Limited</div>
</div>
</div>
</div>
</div>
<div class="tab-content">
<div class="tab-pane fade active in" id="standalone-new">
<div class="table-responsive financial-table">
<table class="mctable1" width="100%">
<tr class="lightbg">
<td>Balance Sheet of Reliance Industries <span class="ttn">(in Rs. Cr.)</span></td>
<td>Mar 23</td>
<td>Mar 22</td>
<td>Mar 21</td>
<td>Mar 20</td>
<td>Mar 19</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td> </td>
<td>12 mths</td>
<td>12 mths</td>
<td>12 mths</td>
<td>12 mths</td>
<td>12 mths</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="darkbg">
<td>EQUITIES AND LIABILITIES</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="darkbg">
<td>SHAREHOLDER'S FUNDS</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Equity Share Capital</td>
<td>6,765.00</td>
<td>6,765.00</td>
<td>6,445.00</td>
<td>6,339.00</td>
<td>6,339.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="lightbg">
<td>Total Share Capital</td>
<td>6,765.00</td>
<td>6,765.00</td>
<td>6,445.00</td>
<td>6,339.00</td>
<td>6,339.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Reserves and Surplus</td>
<td>472,328.00</td>
<td>464,762.00</td>
<td>468,038.00</td>
<td>384,875.00</td>
<td>398,983.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="lightbg">
<td>Total Reserves and Surplus</td>
<td>472,328.00</td>
<td>464,762.00</td>
<td>468,038.00</td>
<td>384,875.00</td>
<td>398,983.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="lightbg">
<td>Total Shareholders Funds</td>
<td>479,093.00</td>
<td>471,527.00</td>
<td>474,483.00</td>
<td>391,214.00</td>
<td>405,322.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="darkbg">
<td>NON-CURRENT LIABILITIES</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Long Term Borrowings</td>
<td>135,561.00</td>
<td>167,231.00</td>
<td>160,598.00</td>
<td>194,402.00</td>
<td>118,098.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Deferred Tax Liabilities [Net]</td>
<td>33,968.00</td>
<td>30,832.00</td>
<td>30,788.00</td>
<td>50,556.00</td>
<td>47,317.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Other Long Term Liabilities</td>
<td>3,370.00</td>
<td>6,504.00</td>
<td>4,518.00</td>
<td>3,434.00</td>
<td>504.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Long Term Provisions</td>
<td>1,296.00</td>
<td>1,598.00</td>
<td>1,499.00</td>
<td>1,410.00</td>
<td>2,483.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="lightbg">
<td>Total Non-Current Liabilities</td>
<td>174,195.00</td>
<td>206,165.00</td>
<td>197,403.00</td>
<td>249,802.00</td>
<td>168,402.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="darkbg">
<td>CURRENT LIABILITIES</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Short Term Borrowings</td>
<td>80,262.00</td>
<td>27,332.00</td>
<td>33,152.00</td>
<td>59,899.00</td>
<td>39,097.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Trade Payables</td>
<td>110,722.00</td>
<td>134,005.00</td>
<td>86,999.00</td>
<td>71,048.00</td>
<td>88,241.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Other Current Liabilities</td>
<td>45,367.00</td>
<td>38,749.00</td>
<td>80,735.00</td>
<td>198,662.00</td>
<td>73,900.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Short Term Provisions</td>
<td>926.00</td>
<td>896.00</td>
<td>901.00</td>
<td>1,073.00</td>
<td>783.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="lightbg">
<td>Total Current Liabilities</td>
<td>237,277.00</td>
<td>200,982.00</td>
<td>201,787.00</td>
<td>330,682.00</td>
<td>202,021.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="lightbg">
<td>Total Capital And Liabilities</td>
<td>890,565.00</td>
<td>878,674.00</td>
<td>873,673.00</td>
<td>971,699.00</td>
<td>775,745.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="darkbg">
<td>ASSETS</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="darkbg">
<td>NON-CURRENT ASSETS</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Tangible Assets</td>
<td>232,238.00</td>
<td>223,824.00</td>
<td>292,092.00</td>
<td>297,854.00</td>
<td>194,895.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Intangible Assets</td>
<td>12,926.00</td>
<td>15,802.00</td>
<td>14,741.00</td>
<td>8,624.00</td>
<td>8,293.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Capital Work-In-Progress</td>
<td>30,958.00</td>
<td>19,267.00</td>
<td>20,765.00</td>
<td>15,638.00</td>
<td>105,155.00</td>
<td class="last_td" style="width:5%;"> </td>
</tr>
<tr class="">
<td>Other Assets</td>

In [ ]:
def balance_sheet(ticker):
    balance_sheet_dict = {}
    balance_sheet = {}
    table_title = {}
#     url = "https://finance.yahoo.com/quote/{}/balance-sheet?p={}".format(ticker,ticker)
    url = "https://www.moneycontrol.com/financials/{}/balance-sheetVI/{}".format(ticker,ticker)
    headers = {"User-Agent" : "Chrome/96.0.4664.110"}
    page = requests.get(url, headers=headers)
    page_content = page.content
    soup = BeautifulSoup(page_content,"html.parser")
#     tabl = soup.find_all("div" , {"class" : "M(0) Whs(n) BdEnd Bdc($seperatorColor) D(itb)"})
    tabl = soup.find_all("div" , {"class" : "M(0) Whs(n) BdEnd Bdc($seperatorColor) D(itb)"})
#     print(tabl)
    
    for t in tabl:
        heading = t.find_all("div" , {"class": "D(tbr) C($primaryColor)"})
        for top_row in heading:
            table_title[top_row.get_text(separator="|").split("|")[0]] = top_row.get_text(separator="|").split("|")[1:]
        rows = t.find_all("div" , {"class": "D(tbr) fi-row Bgc($hoverBgColor):h"})
        for row in rows:
            balance_sheet[row.get_text(separator="|").split("|")[0]] = row.get_text(separator="|").split("|")[1:]

    temp = pd.DataFrame(balance_sheet).T
    temp.columns = table_title["Breakdown"]
    balance_sheet_dict[ticker] = temp
    
    return temp

In [18]:

url = 'https://www.moneycontrol.com/india/stockpricequote/diversified/itc/ITC'
page = requests.get(url)
page

soup = BeautifulSoup(page.text,'lxml')
soup

#price of stock
price = soup.find('div', class_ = 'inprice1 nsecp').text
price

#previous close price of stock
pvcprice = soup.find('td', class_ = 'nseprvclose bseprvclose').text
pvcprice

#52 week range
lower = soup.find('div', class_ = 'FL nseL52').text
lower

'304.50'

#### Stock News

https://www.geeksforgeeks.org/web-scraping-financial-news-using-python/

In [87]:
from bs4 import BeautifulSoup as BS
import requests as req
 
url = "https://www.businesstoday.in/latest/economy"
 
webpage = req.get(url)
trav = BS(webpage.content, "html.parser")
M = 1
for link in trav.find_all('a'):
   
    # PASTE THE CLASS TYPE THAT WE GET
    # FROM THE ABOVE CODE IN THIS AND
    # SET THE LIMIT GREATER THAN 35
    if(str(type(link.string)) == "<class 'bs4.element.NavigableString'>"
       and len(link.string) > 35):
 
        print(str(M)+".", link.string)
        M += 1

1. CEA Nageswaran: 'We’re comfortable with 6.5% GDP growth and we don’t see downside risks arising'
2. 93% of Rs 2,000 notes back with banks, notes worth Rs 24,000 cr remain in circulation: RBI
3. GST collections in August rise 11% to about Rs 1.6 lakh crore
4. 'Incredible milestone': UPI transactions cross 10 billion mark in August
5. Food inflation remains a challenge for FMCG biggies like Nestle, ITC
6. After driest August since 1901, India could receive average rains in September: IMD official
7. Private consumption, capital formation help India ensure robust GDP growth of 7.8% in Q1FY24
8. India's April-July fiscal deficit at Rs 6.06 lakh cr, 33.9% of FY24 target
9. India's GDP growth accelerates to one-year high of 7.8% in Q1FY24
10. NDA vs UPA: How the two governments fared on capex and subsidies in the last 20 years
11. India's economic growth set to accelerate to its fastest in a year: Report
12. G20 Leaders’ Summit: Joe Biden, Rishi Sunak, Emmanuel Macron, Xi Jinping to attend; who will stay where
13. Centre cuts LPG gas cylinder prices by Rs 200, additional subsidy of Rs 200 granted under Ujjwala scheme
14. ‘Need for India, China to increase cooperation on…’: SBI report on the way forward for BRICS+6
15. Moody’s: Population growth not enough to reap economic gains
16. Union Minister Nitin Gadkari shares stunning images of Ranchi-Jamshedpur Expressway
17. Govt decides not to allow basmati rice exports below $1,200 per tonne
18. PM says businesses need to think beyond the bottom line
19. EXCLUSIVE: PM Narendra Modi speaks about India’s growth potential; says economy will ‘deliver unprecedented opportunities’
20. BT EXCLUSIVE: Apple, Micron show India's attractiveness as manufacturing destination, says PM Modi
21. India's forex reserves post steepest weekly decline in over 6 months at $595 bn

In [20]:
# IMPORT ALL LIBRARIES
from bs4 import BeautifulSoup as BS
import requests as req
 
url = "https://www.businesstoday.in/latest/economy"
 
webpage = req.get(url)  # YOU CAN EVEN DIRECTLY PASTE THE URL IN THIS
# HERE HTML PARSER IS ACTUALLY THE WHOLE HTML PAGE
trav = BS(webpage.content, "html.parser")
 
# TO GET THE TYPE OF CLASS
# HERE 'a' STANDS FOR ANCHOR TAG IN WHICH NEWS IS STORED
for link in trav.find_all('a'):
    print(type(link.string), " ", link.string)

<class 'bs4.element.NavigableString'>   Business Today
<class 'bs4.element.NavigableString'>   BT Bazaar
<class 'bs4.element.NavigableString'>   India Today
<class 'bs4.element.NavigableString'>   Northeast
<class 'bs4.element.NavigableString'>   Web3Cafe
<class 'bs4.element.NavigableString'>   DailyO
<class 'bs4.element.NavigableString'>   India Today Gaming
<class 'bs4.element.NavigableString'>   Cosmopolitan
<class 'bs4.element.NavigableString'>   Harper's Bazaar
<class 'bs4.element.NavigableString'>   Brides Today
<class 'bs4.element.NavigableString'>   Ishq FM
<class 'bs4.element.NavigableString'>   Aaj Tak
<class 'bs4.element.NavigableString'>   GNTTV
<class 'bs4.element.NavigableString'>   iChowk
<class 'bs4.element.NavigableString'>   Kisan Tak
<class 'bs4.element.NavigableString'>   Lallantop
<class 'bs4.element.NavigableString'>   Malyalam
<class 'bs4.element.NavigableString'>   Bangla
<class 'bs4.element.NavigableString'>   Sports Tak
<class 'bs4.element.NavigableString'>   Crime Tak
<class 'bs4.element.NavigableString'>   Aajtak Campus
<class 'bs4.element.NavigableString'>   Astro tak
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   Subscribe
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   Home
<class 'bs4.element.NavigableString'>   Magazine
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   BT TV
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   Market Today
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   Tech Today
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   Money Today
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   Mutual Funds
<class 'bs4.element.NavigableString'>   Industry
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   BTShorts
<class 'bs4.element.NavigableString'>   Visual Stories
<class 'bs4.element.NavigableString'>   BT Reels
<class 'bs4.element.NavigableString'>   events
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>    Immersives
<class 'bs4.element.NavigableString'>    UPSTART
<class 'bs4.element.NavigableString'>    Economy
<class 'bs4.element.NavigableString'>    Corporate
<class 'bs4.element.NavigableString'>    Petrol-Diesel
<class 'bs4.element.NavigableString'>    Weather
<class 'bs4.element.NavigableString'>    BT Bazaar
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>    BT-TR GCC Listing
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   Search
<class 'bs4.element.NavigableString'>   INDICES ANALYSIS
<class 'bs4.element.NavigableString'>   AMC FUNDS
<class 'bs4.element.NavigableString'>   MUTUAL FUNDS
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   Subscribe
<class 'bs4.element.NavigableString'>    Home
<class 'bs4.element.NavigableString'>    Magazine
<class 'bs4.element.NavigableString'>   Cover Story
<class 'bs4.element.NavigableString'>   Editor's Note
<class 'bs4.element.NavigableString'>   Deep Dive
<class 'bs4.element.NavigableString'>   Interview
<class 'bs4.element.NavigableString'>   The Buzz
<class 'bs4.element.NavigableString'>    BT TV
<class 'bs4.element.NavigableString'>   Market Today
<class 'bs4.element.NavigableString'>   Easynomics
<class 'bs4.element.NavigableString'>   Drive Today
<class 'bs4.element.NavigableString'>   BT Explainer
<class 'bs4.element.NavigableString'>    Market Today
<class 'bs4.element.NavigableString'>   Indices
<class 'bs4.element.NavigableString'>   Trending Stocks
<class 'bs4.element.NavigableString'>   Stocks List
<class 'bs4.element.NavigableString'>   Company Stocks in News
<class 'bs4.element.NavigableString'>   Share Market News
<class 'bs4.element.NavigableString'>   IPO Corner
<class 'bs4.element.NavigableString'>    Tech Today
<class 'bs4.element.NavigableString'>   Unbox Today
<class 'bs4.element.NavigableString'>   Authen Tech
<class 'bs4.element.NavigableString'>   Tech Deck
<class 'bs4.element.NavigableString'>   Tech Shorts
<class 'bs4.element.NavigableString'>    Money Today
<class 'bs4.element.NavigableString'>   Tax
<class 'bs4.element.NavigableString'>   Investment
<class 'bs4.element.NavigableString'>   Insurance
<class 'bs4.element.NavigableString'>   Tools & Calculator
<class 'bs4.element.NavigableString'>    Mutual Funds
<class 'bs4.element.NavigableString'>    Industry
<class 'bs4.element.NavigableString'>   Banking
<class 'bs4.element.NavigableString'>   IT
<class 'bs4.element.NavigableString'>   Auto
<class 'bs4.element.NavigableString'>   Energy
<class 'bs4.element.NavigableString'>   Commodities
<class 'bs4.element.NavigableString'>   Pharma
<class 'bs4.element.NavigableString'>   Real Estate
<class 'bs4.element.NavigableString'>   Telecom
<class 'bs4.element.NavigableString'>    BTShorts
<class 'bs4.element.NavigableString'>    Visual Stories
<class 'bs4.element.NavigableString'>    BT Reels
<class 'bs4.element.NavigableString'>    Immersives
<class 'bs4.element.NavigableString'>    UPSTART
<class 'bs4.element.NavigableString'>    Economy
<class 'bs4.element.NavigableString'>    Corporate
<class 'bs4.element.NavigableString'>    Petrol-Diesel
<class 'bs4.element.NavigableString'>    Weather
<class 'bs4.element.NavigableString'>    BT Bazaar
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>    BT-TR GCC Listing
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   News
<class 'bs4.element.NavigableString'>   LATEST
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   Feedback
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   G20 Leaders’ Summit: Joe Biden, Rishi Sunak, Emmanuel Macron, Xi Jinping to attend; who will stay where
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   Centre cuts LPG gas cylinder prices by Rs 200, additional subsidy of Rs 200 granted under Ujjwala scheme
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   ‘Need for India, China to increase cooperation on…’: SBI report on the way forward for BRICS+6
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   Moody’s: Population growth not enough to reap economic gains
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   Union Minister Nitin Gadkari shares stunning images of Ranchi-Jamshedpur Expressway
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   Govt decides not to allow basmati rice exports below $1,200 per tonne
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   PM says businesses need to think beyond the bottom line
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   EXCLUSIVE: PM Narendra Modi speaks about India’s growth potential; says economy will ‘deliver unprecedented opportunities’
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   BT EXCLUSIVE: Apple, Micron show India's attractiveness as manufacturing destination, says PM Modi
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   India's forex reserves post steepest weekly decline in over 6 months at $595 bn
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   Fed's Powell: Not yet clear rates are high enough to control inflation
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   B20 Summit: 'Look at India for its strengths and not as China’s alternative,' says FM Sitharaman
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   'Elevated interest rates to come in the way of growth,' cautions FM Sitharaman at B20 Summit
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   Friendshoring a worrisome trend; Indian economy to get bigger over time: WEF President
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   G20 is an economic body, issues of war have implications on economics, says Amitabh Kant at B20 Summit
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   The world must tap into Africa’s agriculture potential for region’s economic development: Sunil Bharti Mittal
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   B20 Summit: Uday Kotak urges companies to earmark 0.2% of profits to meet social development goals
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   N Chandrasekaran makes a compelling case for an India-based international biz institute at key global meet
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   Likely impact of food price shock on overall inflation prompted RBI to keep benchmark rates unchanged: MPC minutes
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   India is the biggest development opportunity of the future: Finance Secretary
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   Australia to discuss progress of FTA with India during its Assistant Trade Minister’s current visit to India
<class 'bs4.element.NavigableString'>   Load More
<class 'bs4.element.NavigableString'>   HOT STOCKS
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   Latest
<class 'bs4.element.NavigableString'>   Must Read
<class 'bs4.element.NavigableString'>   Markets
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   Economy
<class 'bs4.element.NavigableString'>   Corporate
<class 'bs4.element.NavigableString'>   Markets
<class 'bs4.element.NavigableString'>   Trending
<class 'bs4.element.NavigableString'>   Magazine
<class 'bs4.element.NavigableString'>   COVID-19
<class 'bs4.element.NavigableString'>   Infra
<class 'bs4.element.NavigableString'>   Pharma
<class 'bs4.element.NavigableString'>   Real Estate
<class 'bs4.element.NavigableString'>   Stocks
<class 'bs4.element.NavigableString'>   Auto
<class 'bs4.element.NavigableString'>   World
<class 'bs4.element.NavigableString'>   Education
<class 'bs4.element.NavigableString'>   Jobs
<class 'bs4.element.NavigableString'>   Lifestyle
<class 'bs4.element.NavigableString'>   About us
<class 'bs4.element.NavigableString'>   Contact us
<class 'bs4.element.NavigableString'>   Advertise with us
<class 'bs4.element.NavigableString'>   Privacy Policy
<class 'bs4.element.NavigableString'>   Terms and Conditions
<class 'bs4.element.NavigableString'>   Partners
<class 'bs4.element.NavigableString'>   Press Releases
<class 'NoneType'>   None
<class 'bs4.element.NavigableString'>   Add Business Today to Home Screen
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None
<class 'NoneType'>   None

https://stackoverflow.com/questions/73840107/how-web-scrap-html-table-from-money-control-website

In [26]:
import requests
import pandas as pd


url = "https://www.moneycontrol.com/stocks/marketinfo/dividends_declared/"

url = 'https://www.moneycontrol.com/financials/relianceindustries/balance-sheetVI/RI'

data = {"sel_year": "2018", "x": "1", "y": "1"}

all_dfs = []
for data["sel_year"] in range(2018, 2022 + 1):
    df = pd.read_html(requests.post(url, data=data).text)[1]
    df["Year"] = data["sel_year"]
    all_dfs.append(df)

df_out = pd.concat(all_dfs)
print(df_out.head(10))

IndexError: list index out of range

In [32]:
pd.read_html(requests.post(url, data=data).text)[0]

,0,1,2,3,4,5,6
0,Balance Sheet of Reliance Industries (in Rs. Cr.),Mar 23,Mar 22,Mar 21,Mar 20,Mar 19,NaN
1,NaN,12 mths,12 mths,12 mths,12 mths,12 mths,NaN
2,EQUITIES AND LIABILITIES,NaN,NaN,NaN,NaN,NaN,NaN
3,SHAREHOLDER'S FUNDS,NaN,NaN,NaN,NaN,NaN,NaN
4,Equity Share Capital,6765.00,6765.00,6445.00,6339.00,6339.00,NaN
...,...,...,...,...,...,...,...
61,Non-Current Investments Quoted Market Value,2934.00,62401.00,21240.00,27475.00,12937.00,NaN
62,Non-Current Investments Unquoted Book Value,303180.00,273377.00,235348.00,394521.00,259314.00,NaN
63,CURRENT INVESTMENTS,NaN,NaN,NaN,NaN,NaN,NaN
64,Current Investments Quoted Market Value,65984.00,21471.00,36303.00,31814.00,24017.00,NaN
65,Current Investments Unquoted Book Value,20090.00,56833.00,58362.00,38216.00,35623.00,NaN

### Magic Formula

In [10]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [11]:
import requests # for http requests
from bs4 import BeautifulSoup # for html parsing and scraping
from multiprocessing.dummy import Pool as ThreadPool 
import bs4

#### Balance Sheet

In [139]:
def balance_sheet(ticker, ti):
    balance_sheet_dict = {}
    balance_sheet = {}
    table_title = {}

    url = 'https://www.moneycontrol.com/financials/{}/balance-sheetVI/{}'.format(ticker,ti)

    
    data = {"sel_year": "2018", "x": "1", "y": "1"}

    all_dfs = []
    for data["sel_year"] in range(2018, 2023 + 1):
        df = pd.read_html(requests.post(url, data=data).text)[0]
        df["Year"] = data["sel_year"]
        all_dfs.append(df)

    df_out = pd.concat(all_dfs)
#     df_out.columns = df.iloc[0]

#     print(df_out.head(10))
    
    return df_out

In [150]:
fin = []
count = 0
for i in range(len(tickers)):
    count = count + 1
    print(count)
    df = pd.DataFrame()
    df = balance_sheet(tickers[i], ti[i])
    df["Stock"] = tickers[i]
    fin.append(df)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23

In [149]:
# fin

In [151]:
bs = pd.concat(fin)
bs.to_csv("bs_moneycontrol.csv")

In [152]:
# final_data_day = pd.concat(fin, axis = 0)

In [134]:
# final_data_day

In [153]:
# a = balance_sheet("relianceindustries", "RI")
# a["Stock"] = "relianceindustries"
# a

In [154]:
# url = 'https://www.moneycontrol.com/financials/{}/balance-sheetVI/{}'.format("relianceindustries","RI")
# data = {"sel_year": "2018", "x": "1", "y": "1"}

In [155]:
# https://www.moneycontrol.com/financials/relianceindustries/profit-lossVI/RI#RI

In [157]:
def PnL(ticker, ti):
    balance_sheet_dict = {}
    balance_sheet = {}
    table_title = {}

    url = 'https://www.moneycontrol.com/financials/{}/profit-lossVI/{}'.format(ticker,ti)

    
    data = {"sel_year": "2018", "x": "1", "y": "1"}

    all_dfs = []
    for data["sel_year"] in range(2018, 2023 + 1):
        df = pd.read_html(requests.post(url, data=data).text)[0]
        df["Year"] = data["sel_year"]
        all_dfs.append(df)

    df_out = pd.concat(all_dfs)
    df_out.columns = df.iloc[0]

#     print(df_out.head(10))
    
    return df_out

In [161]:
fin = []
count = 0
for i in range(len(tickers)):
    count = count + 1
    print(count, tickers[i])
    df = pd.DataFrame()
    df = PnL(tickers[i], ti[i])
    df["Stock"] = tickers[i]
    fin.append(df)

1 astrallimited
2 aartiindustries
3 balrampurchinimills
4 bhartiairtel
5 bharatheavyelectricals
6 britanniaindustries
7 birlasoft
8 canarabank
9 chambalfertiliserschemicals
10 colgatepalmoliveindia
11 cromptongreavesconsumerelectrical
12 escortskubota
13 gmrairportsinfrastructure
14 hindustanaeronauticsltd
15 havellsindia
16 hdfclifeinsurancecompany
17 ltfinanceholdings
18 marutisuzukiindia
19 maxfinancialservices
20 nmdc
21 piramalenterprises
22 trent
23 vedanta

In [162]:
# a = PnL("relianceindustries", "RI")
pl = pd.concat(fin)
pl.to_csv("pnl_moneycontrol.csv")

In [ ]:
# a.head()

In [ ]:
# https://www.moneycontrol.com/financials/relianceindustries/results/yearly/RI#RI

In [12]:
def inc_statement(ticker, ti):
    balance_sheet_dict = {}
    balance_sheet = {}
    table_title = {}

    url = 'https://www.moneycontrol.com/financials/{}/results/yearly/{}'.format(ticker,ti)

    
    data = {"sel_year": "2018", "x": "1", "y": "1"}

    all_dfs = []
    for data["sel_year"] in range(2018, 2023 + 1):
        df = pd.read_html(requests.post(url, data=data).text)[0]
        df["Year"] = data["sel_year"]
        all_dfs.append(df)

    df_out = pd.concat(all_dfs)
    df_out.columns = df.iloc[0]

#     print(df_out.head(10))
    
    return df_out

In [13]:
fin = []
count = 0
for i in range(len(tickers)):
    count = count + 1
    print(count, tickers[i])
    df = pd.DataFrame()
    df = inc_statement(tickers[i], ti[i])
    df["Stock"] = tickers[i]
    fin.append(df)

1 astrallimited
2 aartiindustries
3 balrampurchinimills

KeyboardInterrupt:

In [ ]:
incs = pd.concat(fin)
incs.to_csv("is_moneycontrol.csv")

In [14]:
pd.read_csv("is_moneycontrol.csv")

,Unnamed: 0,Yearly Results of Astral Limited (in Rs. Cr.),Mar '23,Mar '22,Mar '21,Mar '20,Mar '19,Unnamed: 7,2023,Stock,...,Yearly Results of Max Financial Services (in Rs. Cr.),Unnamed: 45,Yearly Results of NMDC (in Rs. Cr.),Unnamed: 47,Yearly Results of Piramal Enterprises (in Rs. Cr.),Unnamed: 49,Yearly Results of Trent (in Rs. Cr.),Unnamed: 51,Yearly Results of Vedanta (in Rs. Cr.),Unnamed: 53
0,0,Yearly Results of Astral Limited (in Rs. Cr.),Mar '23,Mar '22,Mar '21,Mar '20,Mar '19,NaN,2018,astrallimited,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Net Sales/Income from operations,4611.60,3443.30,2486.30,2042.80,1915.71,NaN,2018,astrallimited,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Other Operating Income,--,--,--,--,--,NaN,2018,astrallimited,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Total Income From Operations,4611.60,3443.30,2486.30,2042.80,1915.71,NaN,2018,astrallimited,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,EXPENDITURE,NaN,NaN,NaN,NaN,NaN,NaN,2018,astrallimited,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6907,45,NaN,--,--,--,--,--,NaN,2023,vedanta,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,- Per. of shares (as a % of the total Share Ca...,NaN
6908,46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,vedanta,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b) Non-encumbered,NaN
6909,47,NaN,--,--,--,--,--,NaN,2023,vedanta,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,- Number of shares (Crores).,NaN
6910,48,NaN,--,--,--,--,--,NaN,2023,vedanta,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,- Per. of shares (as a % of the total sh. of p...,NaN
6911,49,NaN,--,--,--,--,--,NaN,2023,vedanta,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,- Per. of shares (as a % of the total Share Ca...,NaN

In [159]:
# inc = PnL("relianceindustries", "RI")
# inc.head()

In [ ]:
https://www.moneycontrol.com/financials/relianceindustries/cash-flowVI/RI#RI

In [54]:
def cash_flow(ticker, ti):
    balance_sheet_dict = {}
    balance_sheet = {}
    table_title = {}

    url = 'https://www.moneycontrol.com/financials/{}/cash-flowVI/{}'.format(ticker,ti)

    
    data = {"sel_year": "2018", "x": "1", "y": "1"}

    all_dfs = []
    for data["sel_year"] in range(2018, 2023 + 1):
        df = pd.read_html(requests.post(url, data=data).text)[0]
        df["Year"] = data["sel_year"]
        all_dfs.append(df)

    df_out = pd.concat(all_dfs)
    df_out.columns = df.iloc[0]

#     print(df_out.head(10))
    
    return df_out

In [55]:
cf = cash_flow("relianceindustries", "RI")
cf.head()

,Cash Flow of Reliance Industries (in Rs. Cr.),Mar 23,Mar 22,Mar 21,Mar 20,Mar 19,NaN,2023
0,Cash Flow of Reliance Industries (in Rs. Cr.),Mar 23,Mar 22,Mar 21,Mar 20,Mar 19,NaN,2018
1,NaN,12 mths,12 mths,12 mths,12 mths,12 mths,NaN,2018
2,Net Profit/Loss Before Extraordinary Items And...,55572.00,46786.00,27212.00,40316.00,47367.00,NaN,2018
3,Net CashFlow From Operating Activities,48050.00,67491.00,-512.00,77533.00,29191.00,NaN,2018
4,Net Cash Used In Investing Activities,-584.00,-45315.00,74257.00,-143625.00,-53949.00,NaN,2018

In [ ]:
https://www.moneycontrol.com/india/stockpricequote/refineries/relianceindustries/RI

In [85]:
def stock_overview(sector,ticker, ti):
    balance_sheet_dict = {}
    balance_sheet = {}
    table_title = {}

    url = 'https://www.moneycontrol.com/india/stockpricequote/{}/{}/{}'.format(sector[ticker],ticker,ti)

    
    data = {"sel_year": "2018", "x": "1", "y": "1"}

    all_dfs = []
    for i in range(2,6):
        df = pd.read_html(requests.post(url, data=data).text)[i]
        all_dfs.append(df)
      
    df_out = pd.concat(all_dfs)
    df_out.columns = ["Value","Num"]       

    
    return df_out

In [86]:
stock_overview("relianceindustries", "RI")

                          Value                  Num
0                          Open              2406.55
1                Previous Close               2407.0
2                        Volume            9056421.0
3                  Value (Lacs)            218499.74
4                       i  VWAP               2413.4
5                          Beta                  NaN
0                          High              2425.65
1                           Low              2401.65
2                      UC Limit               2647.7
3                      LC Limit               2166.3
4                  52 Week High               2856.0
5                   52 Week Low               2180.0
0  TTM EPS See historical trend  95.71  (-2.47% YoY)
1   TTM PE See historical trend      25.21  (Low PE)
2      P/B See historical trend   1.99 (Average P/B)
3                    Face Value                10.00
0             Mkt Cap (Rs. Cr.)            1632366.0
1                Dividend Yield                 0.37
2                20D Avg Volume            6904756.0
3           20D Avg Delivery(%)                53.12
4                     Sector PE                29.57
5          Book Value Per Share              1213.67

In [59]:
# stock_overview("relianceindustries", "RI")

In [62]:
url = 'https://www.moneycontrol.com/india/stockpricequote/refineries/{}/{}'.format("relianceindustries","RI")

In [64]:
len(pd.read_html(requests.post(url, data=data).text))

69

In [79]:
pd.read_html(requests.post(url, data=data).text)[6]

                0    1
0            Open  - -
1  Previous Close  - -
2          Volume  - -
3     Value(lacs)  - -